language: scala
scala:
  - 2.10.3
branches:
  only:
    # tests unstable... - milestone2
    # tests unstable... - milestone1
    - develop
    - master
notifications:
  irc: "irc.rizon.net#gwlpr"
jdk:
  - openjdk7
  - oraclejdk7
services:
  - mongodb
